title: LeftyDev
description: >
  **LeftyDev** is a small community of SJW-adjacent technology enthusiasts and gamers.
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "lefty-dev"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
